export const seedTopics = [
  {
    slug: "photosynthesis",
    title: "Photosynthesis",
    category: "Biology",
    difficulty: "foundation",
    shortSummary: "How plants turn sunlight, water, and carbon dioxide into food and oxygen.",
    foundation: "Plants need a way to make their own food because they cannot walk around and eat. They use sunlight as their energy source.",
    coreIdea: "Photosynthesis is the process where chlorophyll in plant cells captures light energy and uses it to build glucose from water and carbon dioxide.",
    howItWorks: "Roots pull in water, leaves take in carbon dioxide, and chloroplasts use sunlight to power reactions that create glucose. Oxygen is released as a byproduct.",
    realWorldExample: "A leafy plant near a sunny window grows faster because it has more light available to make food.",
    summary: "Photosynthesis is how plants store solar energy as sugar and release oxygen that many living things depend on.",
    childAnalogy: "It is like a leaf running a tiny solar kitchen.",
    beginnerAnalogy: "It works like a factory that uses sunlight instead of electricity to make fuel.",
    expertNuance: "Light-dependent reactions generate ATP and NADPH, which power carbon fixation in the Calvin cycle.",
    commonConfusions: ["Plants do not eat soil", "Oxygen is produced during the process", "Sunlight provides energy, not matter"],
    reversePrompt: "Explain why sunlight matters even though the plant also needs water and carbon dioxide.",
    keywords: ["sunlight", "glucose", "chlorophyll", "oxygen", "carbon dioxide"]
  },
  {
    slug: "blockchain",
    title: "Blockchain",
    category: "Technology",
    difficulty: "intermediate",
    shortSummary: "A shared record system where data is grouped into linked blocks that are hard to tamper with.",
    foundation: "When many people need to agree on the same history of transactions, they need a record everyone can verify.",
    coreIdea: "A blockchain is a distributed ledger where each block contains transactions and a cryptographic link to the previous block.",
    howItWorks: "Participants validate transactions, package them into blocks, and append them through consensus rules. Changing old data would require changing every later block and convincing the network.",
    realWorldExample: "Cryptocurrency transfers can be verified by many nodes without relying on a single bank database.",
    summary: "Blockchain helps groups maintain a shared, tamper-resistant history without one central controller.",
    childAnalogy: "It is like a class notebook where every page is glued to the page before it.",
    beginnerAnalogy: "Think of it as a Google Sheet copied to many computers, with locks that make edits obvious.",
    expertNuance: "Security depends on consensus assumptions, network incentives, and resistance to reorgs or Byzantine actors.",
    commonConfusions: ["Blockchain is not the same as Bitcoin", "It does not make all data private", "It is not automatically fast or efficient"],
    reversePrompt: "Explain why linking blocks together makes cheating harder.",
    keywords: ["ledger", "block", "consensus", "hash", "distributed"]
  },
  {
    slug: "machine-learning",
    title: "Machine Learning",
    category: "AI",
    difficulty: "intermediate",
    shortSummary: "Systems that learn patterns from data instead of following only hand-written rules.",
    foundation: "Some problems are too varied for fixed rules, so computers learn from examples.",
    coreIdea: "Machine learning trains models on data so they can map inputs to outputs or discover useful structure.",
    howItWorks: "A model starts with adjustable parameters. Training changes those parameters to reduce error on examples, then the model is tested on unseen data.",
    realWorldExample: "An email spam filter learns from examples of spam and non-spam messages.",
    summary: "Machine learning uses data to build models that improve at tasks through training.",
    childAnalogy: "It is like teaching a robot by showing many examples instead of giving every instruction.",
    beginnerAnalogy: "It works like practice worksheets where the system gets feedback and improves over time.",
    expertNuance: "Generalization depends on inductive bias, optimization dynamics, data quality, and regularization.",
    commonConfusions: ["Training is not the same as intelligence", "More data alone does not guarantee quality", "A model can memorize instead of learning well"],
    reversePrompt: "Explain why a model must be tested on new data after training.",
    keywords: ["data", "model", "training", "prediction", "generalization"]
  },
  {
    slug: "black-holes",
    title: "Black Holes",
    category: "Physics",
    difficulty: "advanced",
    shortSummary: "Regions of space where gravity is so strong that not even light can escape past the event horizon.",
    foundation: "Mass bends space and creates gravity. Extremely dense objects bend space dramatically.",
    coreIdea: "A black hole forms when enough mass is compressed into a small region, creating an event horizon around a singularity-like center in classical theory.",
    howItWorks: "If a massive star collapses after exhausting its fuel, gravity can overwhelm outward pressure. The event horizon marks the boundary beyond which escape velocity exceeds the speed of light.",
    realWorldExample: "Astronomers infer black holes by watching nearby stars orbit invisible massive objects or by detecting gravitational waves from mergers.",
    summary: "Black holes are extreme gravitational objects identified through their effects on matter, light, and spacetime.",
    childAnalogy: "It is like a super-deep slide in space that everything nearby keeps slipping into.",
    beginnerAnalogy: "Imagine a valley in a blanket becoming so deep that marbles cannot roll back out.",
    expertNuance: "Descriptions involve general relativity, horizon geometry, accretion physics, and unresolved quantum gravity questions.",
    commonConfusions: ["Black holes do not suck everything in from anywhere", "They can still have finite size", "We detect them indirectly"],
    reversePrompt: "Explain what makes the event horizon different from the center of a black hole.",
    keywords: ["gravity", "event horizon", "mass", "collapse", "spacetime"]
  },
  {
    slug: "compound-interest",
    title: "Compound Interest",
    category: "Finance",
    difficulty: "foundation",
    shortSummary: "Interest earned on both the original money and the interest already added.",
    foundation: "Money in savings can grow when a bank or investment pays interest.",
    coreIdea: "Compound interest means each new interest calculation includes the previous growth, not just the starting principal.",
    howItWorks: "If money earns a percentage return every period, the balance grows, and the next period's return is calculated on the bigger balance.",
    realWorldExample: "Saving 100 dollars with yearly interest grows faster when you leave earlier interest in the account.",
    summary: "Compounding accelerates growth because gains start generating their own gains.",
    childAnalogy: "It is like a snowball that gets bigger and then picks up even more snow.",
    beginnerAnalogy: "It works like earning interest on your interest, not just on your starting money.",
    expertNuance: "Growth follows an exponential pattern determined by principal, rate, compounding frequency, and time horizon.",
    commonConfusions: ["Simple interest is different", "Small rates matter over long periods", "Time is a major multiplier"],
    reversePrompt: "Explain why leaving money invested longer changes the outcome so much.",
    keywords: ["interest", "principal", "rate", "growth", "time"]
  },
  {
    slug: "dna-replication",
    title: "DNA Replication",
    category: "Biology",
    difficulty: "advanced",
    shortSummary: "The process cells use to copy DNA before division.",
    foundation: "Cells need a full copy of genetic instructions before they split into new cells.",
    coreIdea: "DNA replication duplicates the double helix by separating strands and building complementary new strands.",
    howItWorks: "Helicase unwinds DNA, primase lays RNA primers, DNA polymerase extends new strands, and ligase joins fragments on the lagging strand.",
    realWorldExample: "During growth or tissue repair, cells replicate DNA so both daughter cells receive the same genetic blueprint.",
    summary: "DNA replication is a coordinated enzyme-driven copying system that preserves genetic information.",
    childAnalogy: "It is like unzipping a ladder and rebuilding each side using matching puzzle pieces.",
    beginnerAnalogy: "Think of it as copying a two-sided instruction manual by using each old page as a template.",
    expertNuance: "Replication is semiconservative and constrained by antiparallel strand orientation, proofreading, and origin regulation.",
    commonConfusions: ["Replication is not transcription", "Both strands are copied differently", "Proofreading improves fidelity"],
    reversePrompt: "Explain why one DNA strand is copied in fragments.",
    keywords: ["helicase", "polymerase", "template", "semiconservative", "lagging strand"]
  },
  {
    slug: "natural-selection",
    title: "Natural Selection",
    category: "Biology",
    difficulty: "intermediate",
    shortSummary: "Traits that help survival and reproduction tend to become more common over generations.",
    foundation: "Individuals in a species vary, and not all of them survive or reproduce equally.",
    coreIdea: "Natural selection changes populations over time because inherited traits affect reproductive success in particular environments.",
    howItWorks: "Variation exists, some traits help organisms survive or reproduce, those traits are passed on more often, and the population gradually shifts.",
    realWorldExample: "Bacteria exposed to antibiotics can evolve resistance when resistant variants survive and multiply.",
    summary: "Natural selection explains adaptation through differential survival and inheritance.",
    childAnalogy: "It is like the best-fitting shoes getting picked again and again for a long race.",
    beginnerAnalogy: "Useful inherited traits spread because their carriers leave more offspring.",
    expertNuance: "Selection acts on phenotypes, while evolutionary change depends on heritability, variation, and fitness landscapes.",
    commonConfusions: ["Individuals do not evolve during life", "Selection is not goal-directed", "Need and effort do not directly create useful traits"],
    reversePrompt: "Explain why natural selection works on populations instead of changing one animal on its own.",
    keywords: ["variation", "inheritance", "fitness", "population", "adaptation"]
  },
  {
    slug: "api",
    title: "API",
    category: "Software",
    difficulty: "foundation",
    shortSummary: "A defined way for software systems to communicate and request data or actions.",
    foundation: "Programs often need information or services from other programs.",
    coreIdea: "An API is an interface with rules about what requests can be made, what data must be sent, and what response comes back.",
    howItWorks: "A client sends a request to an endpoint with parameters and authentication when needed. The server processes it and returns structured data or an error.",
    realWorldExample: "A weather app asks a weather API for the current forecast in your city.",
    summary: "APIs are contracts that let systems connect predictably.",
    childAnalogy: "It is like ordering food from a menu instead of walking into the kitchen.",
    beginnerAnalogy: "An API is a messenger that carries requests and returns answers in an agreed format.",
    expertNuance: "Design concerns include versioning, idempotency, rate limits, authentication, and schema stability.",
    commonConfusions: ["An API is not always on the internet", "Frontend code is not the API itself", "Endpoints and databases are different layers"],
    reversePrompt: "Explain why software uses an API instead of letting every app touch the database directly.",
    keywords: ["request", "response", "endpoint", "client", "server"]
  },
  {
    slug: "recursion",
    title: "Recursion",
    category: "Computer Science",
    difficulty: "intermediate",
    shortSummary: "A method where a problem is solved by breaking it into smaller versions of itself.",
    foundation: "Some tasks become easier when repeated patterns are handled the same way at smaller scales.",
    coreIdea: "Recursion is when a function calls itself on a reduced problem until it reaches a base case that stops further calls.",
    howItWorks: "The function checks for a base case first. If not reached, it does a smaller call, and the results build back up through the call stack.",
    realWorldExample: "Calculating factorial or traversing folder trees often uses recursion.",
    summary: "Recursion solves self-similar problems by reducing them step by step until stopping conditions are met.",
    childAnalogy: "It is like opening a box that has a smaller box inside until you reach the tiniest one.",
    beginnerAnalogy: "Each step hands a smaller version of the same job to itself.",
    expertNuance: "Practical concerns include stack depth, tail-call behavior, recurrence relations, and iterative alternatives.",
    commonConfusions: ["Recursion must have a base case", "It is not always the fastest choice", "Loops and recursion can solve similar tasks differently"],
    reversePrompt: "Explain what would go wrong if a recursive function had no base case.",
    keywords: ["base case", "call stack", "smaller problem", "function", "termination"]
  },
  {
    slug: "neural-networks",
    title: "Neural Networks",
    category: "AI",
    difficulty: "advanced",
    shortSummary: "Layered mathematical models that transform inputs to outputs by learning weighted patterns.",
    foundation: "Some patterns are too complex for simple rules, especially with images, language, or sound.",
    coreIdea: "Neural networks stack layers of weighted computations and nonlinear activations so they can learn rich representations from data.",
    howItWorks: "Input data passes forward through layers, a loss measures prediction error, and backpropagation updates weights to reduce that error over many training steps.",
    realWorldExample: "Image classifiers learn to identify cats by training on many labeled pictures.",
    summary: "Neural networks learn by adjusting many parameters so useful internal representations emerge.",
    childAnalogy: "It is like many tiny decision helpers passing notes to each other until one gives an answer.",
    beginnerAnalogy: "Think of it as a stack of filters that gradually turn raw input into a final decision.",
    expertNuance: "Behavior depends on architecture, activation functions, optimization, scaling laws, regularization, and data regime.",
    commonConfusions: ["They are not biological brains", "Bigger models are not automatically better", "Training and inference are different phases"],
    reversePrompt: "Explain why the network changes its weights after making mistakes.",
    keywords: ["layers", "weights", "backpropagation", "loss", "representation"]
  },
  {
    slug: "supply-and-demand",
    title: "Supply and Demand",
    category: "Economics",
    difficulty: "foundation",
    shortSummary: "Prices tend to move based on how much of something is available and how much people want it.",
    foundation: "Buyers want goods and sellers offer them, but the amounts on each side can differ.",
    coreIdea: "Demand describes how much consumers want at different prices, and supply describes how much producers offer at different prices.",
    howItWorks: "When demand rises faster than supply, prices often increase. When supply exceeds demand, prices often decrease until markets move toward equilibrium.",
    realWorldExample: "Concert ticket prices rise when many fans want a limited number of seats.",
    summary: "Supply and demand shape price and quantity through buyer and seller behavior.",
    childAnalogy: "It is like many kids wanting the last few cookies on a plate.",
    beginnerAnalogy: "Scarcity pushes prices up, and oversupply pushes them down.",
    expertNuance: "Real markets include elasticity, externalities, regulation, information asymmetry, and frictions.",
    commonConfusions: ["High price does not always mean high demand", "Supply and demand can both move at once", "Equilibrium is a model, not a guarantee"],
    reversePrompt: "Explain why prices can rise even if a product itself has not changed.",
    keywords: ["price", "demand", "supply", "equilibrium", "scarcity"]
  },
  {
    slug: "electric-circuits",
    title: "Electric Circuits",
    category: "Physics",
    difficulty: "foundation",
    shortSummary: "Closed paths that allow electric current to flow through components.",
    foundation: "Electric devices need a complete path for charge to move.",
    coreIdea: "A circuit is a loop where voltage drives current through components such as resistors, bulbs, or motors.",
    howItWorks: "A power source creates potential difference, conductors provide a path, and components use electrical energy. If the path breaks, current stops.",
    realWorldExample: "A flashlight turns on only when the battery, wires, switch, and bulb form a complete loop.",
    summary: "Circuits work when a voltage source pushes charge through a closed path.",
    childAnalogy: "It is like water flowing around a closed track of pipes.",
    beginnerAnalogy: "Voltage pushes, current flows, and resistance slows the flow.",
    expertNuance: "Analysis depends on Ohm's law, Kirchhoff's laws, series-parallel structure, and transient effects.",
    commonConfusions: ["Electricity does not get used up like fuel in a wire", "Open circuits stop current", "Voltage and current are not the same thing"],
    reversePrompt: "Explain why a bulb goes off when the switch opens the circuit.",
    keywords: ["voltage", "current", "resistance", "loop", "battery"]
  },
  {
    slug: "data-structures",
    title: "Data Structures",
    category: "Computer Science",
    difficulty: "intermediate",
    shortSummary: "Ways of organizing data so operations like search, insert, and delete become efficient.",
    foundation: "How data is stored changes how easily a program can use it.",
    coreIdea: "Data structures are organization strategies such as arrays, linked lists, stacks, queues, trees, and hash maps, each optimized for different tasks.",
    howItWorks: "Each structure trades off memory layout, access speed, update cost, and traversal style. Picking the right one depends on the operations you perform most.",
    realWorldExample: "A hash map is useful when you want fast lookup by key, like finding a user by email.",
    summary: "Good data structures make software faster and easier to reason about.",
    childAnalogy: "It is like choosing shelves, boxes, or folders based on what you need to find quickly.",
    beginnerAnalogy: "Different containers make different jobs easier.",
    expertNuance: "Tradeoffs include asymptotic complexity, cache locality, concurrency behavior, and mutation cost.",
    commonConfusions: ["One structure is not best for everything", "Big-O is not the whole story", "Organization affects algorithm design"],
    reversePrompt: "Explain why a programmer might choose a hash map instead of a list.",
    keywords: ["array", "tree", "hash map", "lookup", "complexity"]
  },
  {
    slug: "cybersecurity-basics",
    title: "Cybersecurity Basics",
    category: "Security",
    difficulty: "foundation",
    shortSummary: "Protecting systems, accounts, and data from unauthorized access or damage.",
    foundation: "Computers and online accounts store valuable information that attackers may want.",
    coreIdea: "Cybersecurity combines practices, tools, and policies to reduce risk by preventing, detecting, and responding to attacks.",
    howItWorks: "Strong passwords, multifactor authentication, software updates, encryption, least-privilege access, and monitoring all help reduce common attack paths.",
    realWorldExample: "A company using multifactor authentication makes it harder for stolen passwords to unlock employee accounts.",
    summary: "Cybersecurity is risk management for digital systems.",
    childAnalogy: "It is like using locks, alarms, and rules to protect a house.",
    beginnerAnalogy: "Good security layers defenses so one mistake does not cause total failure.",
    expertNuance: "Threat modeling, defense in depth, incident response, and identity controls are central system design concerns.",
    commonConfusions: ["Security is not only antivirus", "Humans are part of the threat surface", "No system is perfectly secure"],
    reversePrompt: "Explain why one strong password alone is often not enough.",
    keywords: ["authentication", "encryption", "risk", "access", "defense"]
  },
  {
    slug: "climate-change",
    title: "Climate Change",
    category: "Environment",
    difficulty: "intermediate",
    shortSummary: "Long-term shifts in Earth's climate, especially modern warming driven largely by greenhouse gas emissions.",
    foundation: "Earth's temperature depends on how much energy comes in from the sun and how much heat escapes back to space.",
    coreIdea: "Climate change today mainly refers to human-driven warming caused by greenhouse gases trapping more heat in the atmosphere.",
    howItWorks: "Burning fossil fuels and changing land use increase gases such as carbon dioxide and methane. These gases alter Earth's energy balance, affecting temperature, weather patterns, ice, oceans, and ecosystems.",
    realWorldExample: "Rising average temperatures can contribute to more intense heatwaves and shifting rainfall patterns.",
    summary: "Human activity is changing Earth's climate by strengthening the greenhouse effect.",
    childAnalogy: "It is like adding extra blankets around Earth so more heat stays in.",
    beginnerAnalogy: "Greenhouse gases act like a thicker insulating layer around the planet.",
    expertNuance: "Assessment involves radiative forcing, feedback loops, attribution science, uncertainty ranges, and mitigation pathways.",
    commonConfusions: ["Weather and climate are different", "Cold days do not disprove warming", "Natural variability still exists"],
    reversePrompt: "Explain why climate change is about long-term patterns instead of one day of weather.",
    keywords: ["greenhouse gases", "warming", "energy balance", "carbon dioxide", "climate"]
  }
];
