export const LANGUAGE_OPTIONS = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" }
];

export const DEFAULT_UI_COPY = {
  tagline: "Hatch your understanding",
  themeDarkQuest: "Dark Quest",
  themeSunnyQuest: "Sunny Quest",
  themeMoonOn: "Moon On",
  themeSunOn: "Sun On",
  heroTitle: "Learn with long-form teaching, revision cards, and mastery checks.",
  heroBody: "Eggzy now teaches in a fuller journey: deep explanation slides, revision flashcards, MCQ quiz practice, and a teach-back review that spots missing ideas and reteaches them.",
  heroLessons: "Lesson slides",
  heroQuiz: "Quiz mode",
  heroRevise: "Flashcards + teach-back",
  heroMascotTitle: "Eggzy reteaches when you slow down.",
  heroMascotBody: "Long pauses on quiz items, missing concepts in teach-back, and shaky explanations become cues for reteaching.",
  learnerSetupEyebrow: "Learner Setup",
  learnerSetupTitle: "Tell Eggzy how you learn best",
  interestHook: "Interest hook",
  language: "Language",
  learnerName: "Learner name",
  optional: "Optional",
  currentMentalState: "Current mental state",
  explanationStyle: "Preferred explanation style",
  chooseConceptEyebrow: "Choose A Concept",
  chooseConceptTitle: "Start with a topic and let Eggzy teach it step by step",
  conceptPlaceholder: "Examples: fractions, photosynthesis, black holes, microprocessor, blockchain",
  teachMe: "Teach Me",
  teaching: "Teaching...",
  currentMission: "Current Mission",
  learnerSnapshot: "Learner snapshot",
  level: "Level",
  mood: "Mood",
  style: "Style",
  interest: "Interest",
  lessonNavigationEyebrow: "Lesson Navigation",
  lessonNavigationTitle: "Walk through the concept one full screen at a time",
  confusionHotspots: "Confusion hotspots",
  adaptiveCoaching: "Adaptive coaching",
  nextStepEyebrow: "Next Step",
  nextStepTitle: "Choose how you want to revise this lesson",
  revisionChoiceBody: "Pick the path that helps you lock in the concept before moving to teach-back.",
  openQuiz: "Open quiz",
  openFlashcards: "Open flashcards",
  quizChoiceTitle: "Take a mastery check",
  quizChoiceBody: "Use fresh multiple-choice questions to test whether the explanation really clicked.",
  flashcardChoiceTitle: "Review fast with cards",
  flashcardChoiceBody: "Flip through key ideas, definitions, and memory cues before testing yourself.",
  continueToRevision: "Continue to revision",
  revisionHub: "Revision Hub",
  backToExplanation: "Back to explanation",
  backToRevision: "Back to revision choices",
  proceedToTeachBack: "Proceed to teach it to me",
  reviewWithFlashcards: "Review with flashcards",
  retryWithFreshQuiz: "Retry with fresh questions",
  refreshFlashcards: "Refresh flashcards",
  reteachDifferently: "Reteach with a different approach",
  continueToQuiz: "Continue to quiz",
  lessonStrength: "Lesson strength",
  masteryReady: "Mastery ready",
  revisitBeforeTeachBack: "Revisit before teach-back",
  quizCompleteTitle: "Quiz checkpoint",
  quizPerfectBody: "You answered every question correctly. You are ready to teach the topic back to Eggzy.",
  quizRetryBody: "A few ideas still need work. Refresh the quiz, review flashcards, or ask Eggzy to reteach the weak spots.",
  flashcards: "Flashcards",
  reviseQuick: "Revise with quick flips",
  tapPrompt: "Tap to see prompt",
  tapReveal: "Tap to reveal answer",
  previous: "Previous",
  next: "Next",
  quizMode: "Quiz Mode",
  quizTitle: "MCQ practice with hesitation tracking",
  score: "Score",
  needsReteach: "Needs reteach",
  hesitationTitle: "Eggzy noticed hesitation",
  teachTopicEyebrow: "Teach The Topic",
  teachTopicTitle: "Write a full paragraph and let Eggzy spot missing ideas",
  yesMostly: "Yes, mostly",
  notYet: "Not yet",
  slowQuestions: "Slow questions tracked",
  noneYet: "None yet",
  teachBackNavigation: "You can jump back to the explanation, flashcards, or quiz at any time.",
  teachBackPlaceholder: "Teach the topic back in a full paragraph. Eggzy will check what you explained well, what you missed, and what to reteach.",
  confusionPlaceholder: "Still confused about...",
  evaluateUnderstanding: "Evaluate Understanding",
  checking: "Checking...",
  eggzySays: "Eggzy says",
  overlapScore: "Concept overlap score",
  teachBackAnalysis: "Teach-back analysis",
  strong: "Strong",
  missing: "Missing",
  reteach: "Reteach",
  reverseTeachingBank: "Reverse Teaching Bank",
  reverseTeachingTitle: "Questions created from weak spots and skipped ideas",
  starterLibraryEyebrow: "Starter Library",
  starterLibraryTitle: "Browse Eggzy's ready-made quests",
  elementary: "Elementary",
  intermediate: "Intermediate",
  advanced: "Advanced",
  elementarySublabel: "Ages 6-10",
  intermediateSublabel: "Build the basics",
  advancedSublabel: "Domain expertise",
  elementaryDescription: "Simple language, vivid analogies",
  intermediateDescription: "Structured, jargon-free clarity",
  advancedDescription: "Technical depth and nuance",
  elementaryExplanation: "Elementary explanation",
  intermediateExplanation: "Intermediate explanation",
  advancedExplanation: "Advanced explanation",
  analogyLens: "Analogy Lens",
  stepByStepLens: "Step-by-Step Lens",
  realLifeLens: "Real-Life Lens",
  moods: {
    focused: "Focused",
    curious: "Curious",
    overwhelmed: "Overwhelmed",
    tired: "Tired"
  },
  styles: {
    analogy: "Analogy",
    story: "Story",
    technical: "Technical",
    simple: "Simple"
  }
};
