function makeTopic({
  slug,
  title,
  category,
  shortSummary,
  foundation,
  coreIdea,
  howItWorks,
  realWorldExample,
  summary,
  childAnalogy,
  beginnerAnalogy,
  expertNuance,
  commonConfusions,
  reversePrompt,
}) {
  return {
    slug,
    title,
    category,
    shortSummary,
    foundation,
    coreIdea,
    howItWorks,
    realWorldExample,
    summary,
    childAnalogy,
    beginnerAnalogy,
    expertNuance,
    commonConfusions,
    reversePrompt,
  };
}

export const LOCAL_TOPIC_LIBRARY = [
  makeTopic({
    slug: "api",
    title: "API",
    category: "Software",
    shortSummary: "How software systems communicate through structured requests and responses.",
    foundation: "Programs often need information or services from other programs, but they need a safe, predictable way to ask for them.",
    coreIdea: "An API is a defined contract that tells software what it can request, how to request it, and what kind of response it will get back.",
    howItWorks: "A client sends a request to an endpoint, includes needed inputs or authentication, and the server returns data or an action result.",
    realWorldExample: "A weather app uses a weather API to ask for today's forecast without touching the weather company's database directly.",
    summary: "APIs let different software systems work together through clear rules.",
    childAnalogy: "It is like ordering from a menu instead of walking into the kitchen.",
    beginnerAnalogy: "It works like a messenger carrying requests and replies between two programs.",
    expertNuance: "Good APIs need clear schemas, authentication, rate limits, and versioning to stay reliable.",
    commonConfusions: ["An API is not the same as a database", "An API is not always public", "Frontend code calling an API is not the API itself"],
    reversePrompt: "Explain why apps use APIs instead of talking directly to each other's databases.",
  }),
  makeTopic({
    slug: "black-holes",
    title: "Black Holes",
    category: "Physics",
    shortSummary: "Regions of space where gravity is so strong that light cannot escape past the event horizon.",
    foundation: "Mass bends space and creates gravity. Very dense objects bend spacetime dramatically.",
    coreIdea: "A black hole forms when enough mass is squeezed into a small region so that escape beyond the event horizon becomes impossible.",
    howItWorks: "When a massive star collapses or dense matter accumulates, gravity can dominate so strongly that even light cannot escape once it crosses the event horizon.",
    realWorldExample: "Astronomers infer black holes by observing stars orbit invisible heavy objects or by measuring gravitational waves from mergers.",
    summary: "Black holes are extreme gravitational objects known mostly through their effects on nearby matter and light.",
    childAnalogy: "It is like an incredibly deep slide in space that nearby things keep slipping toward.",
    beginnerAnalogy: "Imagine a blanket sagging so deeply that marbles can no longer roll back out.",
    expertNuance: "Descriptions involve general relativity, horizon geometry, accretion physics, and unresolved quantum gravity questions.",
    commonConfusions: ["Black holes do not suck in everything from far away", "The event horizon is not the same as the center", "We usually detect black holes indirectly"],
    reversePrompt: "Explain the difference between a black hole's event horizon and its center.",
  }),
  makeTopic({
    slug: "blockchain",
    title: "Blockchain",
    category: "Technology",
    shortSummary: "A shared tamper-resistant record built from linked blocks of data.",
    foundation: "When many people need to trust the same record, they need a system that makes hidden changes difficult.",
    coreIdea: "A blockchain stores records in blocks that are linked cryptographically so past changes are easy to detect.",
    howItWorks: "Transactions are grouped into blocks, blocks reference previous blocks, and a network follows consensus rules to agree on which chain is valid.",
    realWorldExample: "Cryptocurrency transfers can be checked by many computers without relying on one central bank ledger.",
    summary: "Blockchain helps groups maintain a shared history that is difficult to secretly alter.",
    childAnalogy: "It is like a class notebook where every page is glued to the page before it.",
    beginnerAnalogy: "Think of it as a shared record book copied to many computers, with links that reveal tampering.",
    expertNuance: "Security depends on consensus design, network assumptions, incentives, and data availability.",
    commonConfusions: ["Blockchain is not the same as Bitcoin", "Blockchain is not automatically private", "It is not always fast or efficient"],
    reversePrompt: "Explain how linking blocks makes cheating harder.",
  }),
  makeTopic({
    slug: "climate-change",
    title: "Climate Change",
    category: "Environment",
    shortSummary: "Long-term climate shifts driven largely by greenhouse gas emissions.",
    foundation: "Earth warms and cools depending on how much energy it keeps versus how much it releases.",
    coreIdea: "Modern climate change mainly refers to human-driven warming caused by greenhouse gases trapping extra heat in the atmosphere.",
    howItWorks: "Activities like burning fossil fuels increase gases such as carbon dioxide and methane, changing Earth's energy balance and affecting temperature, oceans, ice, and weather patterns.",
    realWorldExample: "Rising global temperatures can contribute to more intense heat waves and shifts in rainfall patterns.",
    summary: "Human activity is strengthening the greenhouse effect and changing long-term climate patterns.",
    childAnalogy: "It is like adding extra blankets around Earth so more heat stays in.",
    beginnerAnalogy: "Greenhouse gases act like a thicker insulating layer around the planet.",
    expertNuance: "The topic involves radiative forcing, feedback loops, attribution science, uncertainty ranges, and mitigation pathways.",
    commonConfusions: ["Weather and climate are different", "Cold days do not disprove warming", "Natural variability still exists within climate change"],
    reversePrompt: "Explain why climate change is about long-term patterns rather than one day's weather.",
  }),
  makeTopic({
    slug: "compound-interest",
    title: "Compound Interest",
    category: "Finance",
    shortSummary: "Growth that happens when earnings start earning more earnings.",
    foundation: "Money can grow over time when it earns interest.",
    coreIdea: "Compound interest means new interest is calculated on both the original amount and the interest already added.",
    howItWorks: "Each time interest is added, the total balance becomes larger, so the next round of interest is earned on a bigger amount.",
    realWorldExample: "Savings grow much faster over many years when early interest stays invested instead of being withdrawn.",
    summary: "Compounding speeds up growth because gains begin creating more gains.",
    childAnalogy: "It is like a snowball that gets bigger and then picks up even more snow.",
    beginnerAnalogy: "You earn interest on your interest, not only on your starting money.",
    expertNuance: "Compounding follows exponential growth shaped by rate, time horizon, and compounding frequency.",
    commonConfusions: ["Compound interest is different from simple interest", "Small rates matter over long periods", "Time is one of the biggest multipliers"],
    reversePrompt: "Explain why leaving money invested longer matters so much with compounding.",
  }),
  makeTopic({
    slug: "cybersecurity-basics",
    title: "Cybersecurity Basics",
    category: "Security",
    shortSummary: "Protecting systems, accounts, and data from attacks and misuse.",
    foundation: "Digital systems hold valuable information that attackers may try to steal, change, or disrupt.",
    coreIdea: "Cybersecurity reduces digital risk through prevention, detection, and response.",
    howItWorks: "Layers like strong passwords, multifactor authentication, updates, encryption, monitoring, and access control make attacks harder and damage smaller.",
    realWorldExample: "A company with multifactor authentication protects accounts even if a password gets stolen.",
    summary: "Cybersecurity is risk management for digital systems.",
    childAnalogy: "It is like using locks, alarms, and rules to protect a house.",
    beginnerAnalogy: "Good security uses many layers so one mistake does not break everything.",
    expertNuance: "Modern security depends on threat modeling, identity, least privilege, monitoring, and incident response.",
    commonConfusions: ["Security is not only antivirus", "People are part of security too", "No system is perfectly secure"],
    reversePrompt: "Explain why one strong password is useful but not enough by itself.",
  }),
  makeTopic({
    slug: "data-structures",
    title: "Data Structures",
    category: "Computer Science",
    shortSummary: "Ways to organize data so programs can access and update it efficiently.",
    foundation: "How data is stored changes how easily a program can use it.",
    coreIdea: "Data structures are patterns for organizing information, each designed to make some operations easier than others.",
    howItWorks: "Arrays, linked lists, stacks, queues, trees, and hash maps each trade off memory layout, access speed, update cost, and traversal style.",
    realWorldExample: "A hash map helps you quickly find a user profile by email instead of checking every item one by one.",
    summary: "Good data structures make software faster and easier to reason about.",
    childAnalogy: "It is like choosing between shelves, drawers, and folders based on what you need to find quickly.",
    beginnerAnalogy: "Different containers make different data jobs easier.",
    expertNuance: "Tradeoffs include asymptotic complexity, cache locality, mutation cost, and concurrency behavior.",
    commonConfusions: ["No one structure is best for every task", "Big-O is helpful but not the whole story", "Data structure choice shapes algorithm design"],
    reversePrompt: "Explain why a programmer might choose a hash map instead of a list.",
  }),
  makeTopic({
    slug: "databases",
    title: "Databases",
    category: "Software",
    shortSummary: "Systems built to store, organize, and retrieve data reliably.",
    foundation: "Applications need a safe place to keep information after a page refresh or app restart.",
    coreIdea: "A database is specialized software for storing structured or semi-structured data so it can be queried, updated, and protected efficiently.",
    howItWorks: "Applications send create, read, update, and delete operations, while the database handles storage, indexing, concurrency, and consistency rules.",
    realWorldExample: "An e-commerce app stores products, orders, and customer accounts in a database.",
    summary: "Databases help apps keep data organized, persistent, and searchable.",
    childAnalogy: "It is like a giant smart filing cabinet for app information.",
    beginnerAnalogy: "A database is a memory system that helps software save and find information reliably.",
    expertNuance: "Database design involves schema modeling, transactions, indexing, query planning, and tradeoffs between consistency and scale.",
    commonConfusions: ["A database is different from an API", "A spreadsheet is not the same as a production database", "Storage and querying are separate concerns"],
    reversePrompt: "Explain why most apps use databases instead of keeping everything only in frontend memory.",
  }),
  makeTopic({
    slug: "dna-replication",
    title: "DNA Replication",
    category: "Biology",
    shortSummary: "How cells copy DNA before dividing.",
    foundation: "Cells must copy their genetic instructions before making new cells.",
    coreIdea: "DNA replication duplicates the double helix by separating strands and building complementary new strands.",
    howItWorks: "Helicase unwinds DNA, primers mark starting points, polymerases build new strands, and ligase seals fragments together.",
    realWorldExample: "During growth and tissue repair, cells replicate DNA so both daughter cells receive the same instructions.",
    summary: "DNA replication is a careful copying system that preserves genetic information.",
    childAnalogy: "It is like unzipping a ladder and rebuilding each side with matching pieces.",
    beginnerAnalogy: "Each original DNA strand acts like a template for making a new partner strand.",
    expertNuance: "Replication is semiconservative and constrained by antiparallel orientation, proofreading, and origin regulation.",
    commonConfusions: ["Replication is not transcription", "Leading and lagging strands are copied differently", "Proofreading improves fidelity"],
    reversePrompt: "Explain why one DNA strand is copied in fragments.",
  }),
  makeTopic({
    slug: "electric-circuits",
    title: "Electric Circuits",
    category: "Physics",
    shortSummary: "Closed paths that allow electric current to flow through components.",
    foundation: "Electrical devices need a complete path for charge to move.",
    coreIdea: "A circuit is a closed loop where voltage drives current through components.",
    howItWorks: "A source creates potential difference, wires provide a path, and components like bulbs or resistors use electrical energy as charge flows.",
    realWorldExample: "A flashlight turns on only when the battery, switch, bulb, and wires form a complete loop.",
    summary: "Circuits work when charge can move through a complete path.",
    childAnalogy: "It is like water flowing around a closed pipe loop.",
    beginnerAnalogy: "Voltage pushes, current flows, and resistance slows the flow.",
    expertNuance: "Circuit analysis uses Ohm's law, Kirchhoff's laws, network topology, and transient behavior.",
    commonConfusions: ["Voltage and current are not the same", "Open circuits stop current", "Electricity in wires is not used up like fuel"],
    reversePrompt: "Explain why a bulb goes off when the switch opens the circuit.",
  }),
  makeTopic({
    slug: "fractions",
    title: "Fractions",
    category: "Mathematics",
    shortSummary: "Numbers that represent parts of a whole or ratios between quantities.",
    foundation: "Sometimes one whole thing needs to be split into equal parts.",
    coreIdea: "A fraction uses a numerator and denominator to show how many parts are being considered out of a total number of equal parts.",
    howItWorks: "The denominator tells how many equal pieces make the whole, and the numerator tells how many of those pieces are being counted.",
    realWorldExample: "If a pizza is cut into 8 equal slices and you eat 3, you ate 3/8 of the pizza.",
    summary: "Fractions describe equal parts of a whole and relationships between quantities.",
    childAnalogy: "It is like counting slices from a cake cut into equal pieces.",
    beginnerAnalogy: "Fractions are part-counts built from equal-sized pieces.",
    expertNuance: "Fractions connect to ratios, rational numbers, equivalence classes, and proportional reasoning.",
    commonConfusions: ["Bigger denominators mean smaller pieces", "Fractions can represent ratios, not just pieces of food", "Equivalent fractions can look different but mean the same amount"],
    reversePrompt: "Explain why 1/4 is smaller than 1/3 even though 4 is bigger than 3.",
  }),
  makeTopic({
    slug: "gravity",
    title: "Gravity",
    category: "Physics",
    shortSummary: "The attraction between masses that shapes falling objects, planets, and galaxies.",
    foundation: "Objects near Earth fall downward because Earth pulls on them.",
    coreIdea: "Gravity is the attraction between masses, and larger masses create stronger gravitational effects.",
    howItWorks: "Every mass pulls on every other mass. Near planets this pull causes falling, while in space it shapes orbits and large-scale structure.",
    realWorldExample: "Earth's gravity keeps the Moon in orbit and keeps us standing on the ground.",
    summary: "Gravity is a universal attraction that governs motion from dropped objects to planets.",
    childAnalogy: "It is like a giant invisible pull that keeps things from floating away.",
    beginnerAnalogy: "Bigger masses tug harder, and nearby objects feel that pull more strongly.",
    expertNuance: "Modern descriptions include Newtonian gravity as an approximation and general relativity for spacetime curvature.",
    commonConfusions: ["Gravity does not require air", "Astronauts in orbit still feel gravity", "Weight and mass are related but not identical"],
    reversePrompt: "Explain why astronauts orbit Earth instead of simply floating far away.",
  }),
  makeTopic({
    slug: "internet",
    title: "Internet",
    category: "Technology",
    shortSummary: "A global network of networks that lets devices exchange information.",
    foundation: "Computers can be connected so they can share messages and data.",
    coreIdea: "The internet is a worldwide system of connected networks that uses common protocols to move data between devices.",
    howItWorks: "Information is broken into packets, routed across many networks, and reassembled at the destination using shared rules like TCP/IP.",
    realWorldExample: "When you open a website, your device sends requests across the internet to a server and receives page data back.",
    summary: "The internet works by moving packets through connected networks using common communication rules.",
    childAnalogy: "It is like many roads connecting houses so letters can travel between them.",
    beginnerAnalogy: "The internet is a worldwide delivery system for digital packets.",
    expertNuance: "Internet behavior depends on routing, DNS, transport protocols, peering, latency, and infrastructure resilience.",
    commonConfusions: ["The internet is not the same as the web", "Wi-Fi is not the internet itself", "Data often travels through many intermediate networks"],
    reversePrompt: "Explain why the internet is bigger than just websites and browsers.",
  }),
  makeTopic({
    slug: "machine-learning",
    title: "Machine Learning",
    category: "AI",
    shortSummary: "Systems that learn patterns from data instead of fixed rules.",
    foundation: "Some tasks are too varied for strict if-then rules, so examples become useful teachers.",
    coreIdea: "Machine learning trains models on data so they can make predictions or detect structure.",
    howItWorks: "A model adjusts internal parameters during training to reduce error on examples and is then tested on new unseen data.",
    realWorldExample: "Spam filters learn from labeled examples of spam and non-spam emails.",
    summary: "Machine learning builds models that improve through training on data.",
    childAnalogy: "It is like teaching a robot by showing lots of examples.",
    beginnerAnalogy: "The system practices on data and learns patterns from feedback.",
    expertNuance: "Performance depends on data quality, inductive bias, optimization, regularization, and generalization.",
    commonConfusions: ["Training is not the same as intelligence", "More data alone is not enough", "A model can memorize instead of generalizing"],
    reversePrompt: "Explain why testing on new data matters after training.",
  }),
  makeTopic({
    slug: "mitosis",
    title: "Mitosis",
    category: "Biology",
    shortSummary: "The process cells use to divide into two similar daughter cells.",
    foundation: "Living things need new cells for growth, repair, and replacement.",
    coreIdea: "Mitosis is the stage of cell division where copied chromosomes are separated so each new cell gets a full set.",
    howItWorks: "After DNA is copied, chromosomes condense, line up, separate into two groups, and the cell splits into two daughter cells.",
    realWorldExample: "Skin cells use mitosis to replace damaged or worn-out cells.",
    summary: "Mitosis helps organisms grow and repair tissues by making similar new cells.",
    childAnalogy: "It is like one classroom splitting its full set of books into two new classrooms.",
    beginnerAnalogy: "The cell carefully sorts one copied instruction set into two matching packages.",
    expertNuance: "The process includes spindle formation, chromosome segregation, and checkpoints that reduce division errors.",
    commonConfusions: ["Mitosis is different from meiosis", "DNA is copied before mitosis, not during it", "The goal is similar daughter cells"],
    reversePrompt: "Explain why DNA must be copied before mitosis starts.",
  }),
  makeTopic({
    slug: "natural-selection",
    title: "Natural Selection",
    category: "Biology",
    shortSummary: "How helpful inherited traits become more common across generations.",
    foundation: "Individuals vary, and not all survive or reproduce equally.",
    coreIdea: "Natural selection changes populations because inherited traits affect reproductive success in a specific environment.",
    howItWorks: "Variation exists, some traits help more than others, and traits linked to higher reproduction tend to become more common over generations.",
    realWorldExample: "Antibiotic-resistant bacteria survive treatments and then multiply more successfully than non-resistant bacteria.",
    summary: "Natural selection explains how populations adapt over generations.",
    childAnalogy: "It is like the best-fitting shoes being chosen again and again for a long race.",
    beginnerAnalogy: "Helpful inherited traits spread because their carriers leave more offspring.",
    expertNuance: "Selection acts on phenotypes while evolutionary response depends on heritability, variation, and fitness landscapes.",
    commonConfusions: ["Individuals do not evolve during life", "Selection is not goal-directed", "Need does not directly create new helpful traits"],
    reversePrompt: "Explain why natural selection changes populations instead of changing one animal by effort.",
  }),
  makeTopic({
    slug: "neural-networks",
    title: "Neural Networks",
    category: "AI",
    shortSummary: "Layered models that learn weighted patterns from data.",
    foundation: "Some patterns in language, images, and sound are too complex for simple rules.",
    coreIdea: "Neural networks use many weighted layers and nonlinear transformations to learn useful representations from data.",
    howItWorks: "Inputs move forward through layers, loss measures error, and backpropagation updates weights so later predictions improve.",
    realWorldExample: "An image classifier learns to identify cats by training on many labeled pictures.",
    summary: "Neural networks learn by adjusting many parameters until useful internal patterns emerge.",
    childAnalogy: "It is like many tiny helpers passing notes until one final answer appears.",
    beginnerAnalogy: "A neural network is a stack of filters that gradually turns raw input into a decision.",
    expertNuance: "Behavior depends on architecture, optimization, activations, data regime, regularization, and scaling.",
    commonConfusions: ["Neural networks are not actual brains", "Bigger models are not automatically better", "Training and inference are different"],
    reversePrompt: "Explain why a neural network changes its weights after making mistakes.",
  }),
  makeTopic({
    slug: "osmosis",
    title: "Osmosis",
    category: "Biology",
    shortSummary: "The movement of water across a membrane from lower solute concentration to higher solute concentration.",
    foundation: "Cells are surrounded by membranes, and water often needs to move in or out.",
    coreIdea: "Osmosis is the net movement of water through a semipermeable membrane toward the side with more dissolved particles.",
    howItWorks: "Water molecules move randomly, but more move toward the side where free water is less available because more solute is present.",
    realWorldExample: "Raisins swell in water because water moves into them through their skin.",
    summary: "Osmosis balances water concentration across membranes.",
    childAnalogy: "It is like water sneaking through a tiny fence to the thirstier side.",
    beginnerAnalogy: "Water moves toward the side with more dissolved stuff.",
    expertNuance: "Osmosis is driven by chemical potential differences and is influenced by membrane permeability and osmotic pressure.",
    commonConfusions: ["It is about water movement, not solute movement", "Membranes matter", "Higher concentration means more solute, not more water"],
    reversePrompt: "Explain why water moves into a raisin when you soak it.",
  }),
  makeTopic({
    slug: "photosynthesis",
    title: "Photosynthesis",
    category: "Biology",
    shortSummary: "How plants turn sunlight, water, and carbon dioxide into food.",
    foundation: "Plants need a way to make food because they cannot go and eat like animals.",
    coreIdea: "Photosynthesis captures light energy and uses it to build glucose from water and carbon dioxide.",
    howItWorks: "Roots absorb water, leaves take in carbon dioxide, and chloroplasts use sunlight to power reactions that make glucose and release oxygen.",
    realWorldExample: "A plant near a sunny window often grows better because it has more light to make food.",
    summary: "Photosynthesis stores solar energy in sugar and releases oxygen.",
    childAnalogy: "It is like a tiny solar kitchen inside a leaf.",
    beginnerAnalogy: "Plants run a sunlight-powered factory that makes fuel.",
    expertNuance: "Light-dependent reactions generate ATP and NADPH, which support carbon fixation in the Calvin cycle.",
    commonConfusions: ["Plants do not eat soil", "Sunlight provides energy, not matter", "Oxygen is released during the process"],
    reversePrompt: "Explain why sunlight matters even though plants also need water and carbon dioxide.",
  }),
  makeTopic({
    slug: "plate-tectonics",
    title: "Plate Tectonics",
    category: "Earth Science",
    shortSummary: "The theory that Earth's outer shell is broken into moving plates.",
    foundation: "Earth's surface is not one unbroken shell; it has large sections that move slowly.",
    coreIdea: "Plate tectonics explains earthquakes, volcanoes, mountain building, and continental movement through shifting lithospheric plates.",
    howItWorks: "Plates move over the softer mantle and interact at boundaries where they collide, separate, or slide past one another.",
    realWorldExample: "The Himalayas formed where large plates collided, and many earthquakes happen along plate boundaries.",
    summary: "Plate tectonics explains major geological activity through moving crustal plates.",
    childAnalogy: "It is like giant puzzle pieces slowly drifting and bumping into each other.",
    beginnerAnalogy: "Earth's crust behaves like moving plates floating over a softer layer below.",
    expertNuance: "Mechanisms involve lithosphere dynamics, mantle convection, slab pull, ridge push, and complex boundary interactions.",
    commonConfusions: ["Continents are not the plates themselves", "Plates move slowly but still cause powerful events", "Not all volcanoes are at the same type of boundary"],
    reversePrompt: "Explain why earthquakes often happen near plate boundaries.",
  }),
  makeTopic({
    slug: "probability",
    title: "Probability",
    category: "Mathematics",
    shortSummary: "A way to measure how likely an event is to happen.",
    foundation: "Some outcomes are uncertain, but we can still describe how likely they are.",
    coreIdea: "Probability assigns a number between 0 and 1 to represent the likelihood of an event.",
    howItWorks: "You compare favorable outcomes with total possible outcomes, while also considering assumptions like fairness and independence.",
    realWorldExample: "A fair coin has a probability of 1/2 for landing heads on one flip.",
    summary: "Probability helps us reason about uncertainty using numbers.",
    childAnalogy: "It is like guessing how likely a colored marble is to come out of a bag.",
    beginnerAnalogy: "Probability measures chance by comparing what you want to all possible outcomes.",
    expertNuance: "Formal probability includes distributions, conditional probability, random variables, and inference under uncertainty.",
    commonConfusions: ["Probability is not certainty", "Independent events do not remember previous outcomes", "Small probabilities can still happen"],
    reversePrompt: "Explain why getting heads three times in a row does not force the next coin flip to be tails.",
  }),
  makeTopic({
    slug: "recursion",
    title: "Recursion",
    category: "Computer Science",
    shortSummary: "Solving a problem by reducing it into smaller versions of itself.",
    foundation: "Some problems repeat the same structure at smaller scales.",
    coreIdea: "Recursion happens when a function solves a smaller version of the same problem until it reaches a base case.",
    howItWorks: "The function checks for a stopping condition first. If it has not stopped, it calls itself on a reduced input, and the results build back up.",
    realWorldExample: "Traversing folders inside folders or computing factorials often uses recursion.",
    summary: "Recursion solves self-similar problems by reducing them until a stopping point is reached.",
    childAnalogy: "It is like opening a box with a smaller box inside until you reach the tiniest one.",
    beginnerAnalogy: "Each step hands a smaller version of the same job to itself.",
    expertNuance: "Important concerns include base cases, recursion depth, tail calls, and iterative equivalents.",
    commonConfusions: ["Recursion always needs a base case", "It is not always the fastest option", "Recursion and loops can solve similar problems differently"],
    reversePrompt: "Explain what goes wrong if a recursive function has no base case.",
  }),
  makeTopic({
    slug: "solar-system",
    title: "Solar System",
    category: "Astronomy",
    shortSummary: "The Sun and the objects that orbit it, including planets, moons, asteroids, and comets.",
    foundation: "Our planet is part of a larger neighborhood in space centered on the Sun.",
    coreIdea: "The solar system is a gravitational system with the Sun at the center and many objects orbiting around it.",
    howItWorks: "The Sun's gravity holds planets and smaller bodies in orbit, while each object follows its own path based on motion and mass.",
    realWorldExample: "Earth orbits the Sun once each year while the Moon orbits Earth.",
    summary: "The solar system is a family of space objects organized mostly by the Sun's gravity.",
    childAnalogy: "It is like a giant cosmic family moving around a bright campfire.",
    beginnerAnalogy: "The Sun is the main anchor, and planets are members of the system orbiting it.",
    expertNuance: "The system includes orbital dynamics, formation history, resonances, and diverse minor-body populations.",
    commonConfusions: ["Planets do not orbit randomly", "The Sun is a star", "Moons orbit planets while planets orbit the Sun"],
    reversePrompt: "Explain why Earth stays in orbit around the Sun instead of flying away in a straight line.",
  }),
  makeTopic({
    slug: "sorting-algorithms",
    title: "Sorting Algorithms",
    category: "Computer Science",
    shortSummary: "Methods for arranging data into a chosen order efficiently.",
    foundation: "Programs often need lists arranged so information becomes easier to search and understand.",
    coreIdea: "Sorting algorithms reorder items based on comparison rules, but different algorithms trade off speed, memory use, and stability.",
    howItWorks: "Some methods compare nearby items repeatedly, while others divide data into smaller parts or use extra structures to place values faster.",
    realWorldExample: "An online store sorts products by price, rating, or newest first.",
    summary: "Sorting algorithms organize data, and the best choice depends on the situation.",
    childAnalogy: "It is like putting books in order by size or alphabet.",
    beginnerAnalogy: "Sorting algorithms are recipes for rearranging a list correctly.",
    expertNuance: "Important tradeoffs include time complexity, space complexity, stability, and data distribution assumptions.",
    commonConfusions: ["Fastest in theory is not always fastest in practice", "Stable and unstable sorts behave differently", "Sorted data can make some algorithms much faster"],
    reversePrompt: "Explain why one sorting algorithm might be better for small lists than for huge ones.",
  }),
  makeTopic({
    slug: "supply-and-demand",
    title: "Supply and Demand",
    category: "Economics",
    shortSummary: "How availability and desire influence prices and quantities.",
    foundation: "Buyers and sellers may want different amounts at different prices.",
    coreIdea: "Demand describes how much buyers want, while supply describes how much sellers offer.",
    howItWorks: "When demand rises faster than supply, prices often increase. When supply is higher than demand, prices often fall.",
    realWorldExample: "Concert ticket prices often rise when many fans want a limited number of seats.",
    summary: "Supply and demand shape prices and quantities through buyer and seller behavior.",
    childAnalogy: "It is like many kids wanting the last few cookies on a plate.",
    beginnerAnalogy: "Scarcity pushes prices up, while oversupply tends to push them down.",
    expertNuance: "Real markets involve elasticity, information asymmetry, regulation, and frictions that complicate the simple model.",
    commonConfusions: ["High price does not always mean high demand", "Supply and demand can both shift at once", "Equilibrium is a model, not a guarantee"],
    reversePrompt: "Explain why prices can rise even when the product itself has not changed.",
  }),
  makeTopic({
    slug: "vaccines",
    title: "Vaccines",
    category: "Biology",
    shortSummary: "Medical tools that train the immune system to recognize and fight specific pathogens.",
    foundation: "The immune system protects the body better when it can recognize threats quickly.",
    coreIdea: "Vaccines prepare immune memory without causing the full disease they are meant to prevent.",
    howItWorks: "A vaccine presents the immune system with a safe version or part of a pathogen, triggering antibodies and memory responses for faster defense later.",
    realWorldExample: "A vaccinated person can often fight off an infection faster or avoid severe illness because their immune system has trained for it.",
    summary: "Vaccines help the body prepare defenses before a real infection happens.",
    childAnalogy: "It is like giving your body a practice drill before the real emergency.",
    beginnerAnalogy: "Vaccines train immune memory so the body responds faster next time.",
    expertNuance: "Protection depends on antigen design, immune memory, efficacy, booster timing, and population-level coverage.",
    commonConfusions: ["Vaccines do not mean zero risk in all cases", "Mild reactions are different from the disease itself", "Immune training takes time after vaccination"],
    reversePrompt: "Explain why vaccines can still be useful even if they do not prevent every infection completely.",
  }),
  makeTopic({
    slug: "cloud-computing",
    title: "Cloud Computing",
    category: "Technology",
    shortSummary: "Using remote computing resources over the internet instead of only local machines.",
    foundation: "Apps often need storage and computing power beyond one personal computer.",
    coreIdea: "Cloud computing provides servers, storage, databases, and software services on demand over the internet.",
    howItWorks: "A provider runs large data centers, and customers rent or use resources as needed rather than buying and maintaining everything themselves.",
    realWorldExample: "A startup can deploy its app to cloud servers instead of buying physical hardware upfront.",
    summary: "Cloud computing makes scalable digital infrastructure available as a service.",
    childAnalogy: "It is like renting a big workshop only when you need it instead of building one at home.",
    beginnerAnalogy: "The cloud lets you use computing power from remote providers when you need it.",
    expertNuance: "Important topics include elasticity, multitenancy, orchestration, managed services, cost control, and shared responsibility.",
    commonConfusions: ["The cloud still uses physical computers", "Cloud is not only storage", "Using cloud does not remove security responsibility"],
    reversePrompt: "Explain why many teams choose cloud services instead of buying all their own servers.",
  }),
];
